### PR TITLE
Relax dependency versions for opentelemetry deps 

### PR DESCRIPTION
**Pull request by mosic**
I ran into this while trying to update `opentelemetry_api` in this PR: https://github.com/primait/prima_opentelemetry_ex/pull/23

```
Failed to use "opentelemetry_api" (version 1.1.0) because
  opentelemetry (version 1.1.1) requires ~> 1.1
  opentelemetry_absinthe (version 1.0.0) requires ~> 1.0
  opentelemetry_ecto (version 1.0.0) requires ~> 1.0
  opentelemetry_exporter (version 1.1.1) requires ~> 1.1
  teleplug (version 1.0.0) requires ~> 1.0.0
  mix.lock specifies 1.1.0
```

I also updated opentelemetry deps and bumped up the version number.

### CODE REVIEW

**Review by Fs00 — COMMENTED** [review]
Thanks! I would just bump the teleplug version to 1.0.1 since we are not adding any new features to the library

**Comment by mosic** [comment]
Fair enough, updated to 1.0.1 👍

**Review by Fs00 — APPROVED** [review]

**Comment by mosic** [comment]
@Fs00 Can you merge it as well? UK devs don't have the required permissions in this repo.

**Comment by Fs00** [comment]
Released version 1.0.1 on hex.pm

**Comment by mosic** [comment]
Thanks guys!

**Pull request merged**
