### PR TITLE
Add telepoison dep(optional)

### PR DESCRIPTION
**Pull request by omar8792**
Using teleplug with telepoison `0.1.1` generate an error: 
```
ot_propagation.http_inject is not defined module :ot_propagation is not available 
```

### CODE REVIEW

**Review by francesco-bracchi — COMMENTED** [review]
:thinking: although the fix may work, I don't think it is the right solution (i.e. add an optional dependency that is never used).
It seems that the problem is the dependency on telemetry: some of the two packages do not express correcly dependency over telemetry, (maintainers renamed all the `ot_...` modules in `otel...` modules at some point...)

**Comment by mbusi** [comment]
Yeah you are supposed to update all the deps to the 1.0.0-rc.2 compatible ones
(Ping me if you need help, we are working on it)
Would you kindly close this pr? :D

**Comment by mbusi** [comment]
I guess I can close it for you :D

**Comment by omar8792** [comment]
> I guess I can close it for you :D

Yes, thanks!

**Pull request closed without merging**
